spring:
  application:
    name: spring-stream-backed
  datasource:
    url: jdbc:postgresql://localhost:5432/videoStreamDB
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

files:
  video: videos/

newFile:
  video:
    hls: videos_hls/



# Maximum file size allowed for a single file upload
#  spring.servlet.multipart.max-file-size=1000MB

  # Maximum request size allowed for multipart/form-data requests
#  spring.servlet.multipart.max-request-size=1000MB